### ISSUE TITLE
string vs string_view

### ISSUE THREAD

**Issue by redboltz** [redboltz/mqtt_cpp#289] opened 2019-06-18 01:00 UTC
@jonesmz 

I'd like to discuss the basic policy when we should use string and string_view.
It is very important topic for mqtt_cpp future design.

On #288 You replaced `string_view` with `string`.

https://github.com/redboltz/mqtt_cpp/pull/288/files#diff-fb34b0648e8305bfbb9341f712ec680bR97

I guess that the reason as follows:

The updated code can move construct `buf_`. It is efficient.

```cpp
struct binary_property {
    binary_property(std::string str):buf_(std::move(str)) {}
    std::string const& val() const { return buf_; }
    std::string buf_;
};
```

The original code is as follows:

```cpp
struct binary_property {
    binary_property(string_view sv):buf_(sv.begin(), sv.end()) {}
    string_view val() const { return buf_; }
    std::string buf_;
};
```

It requires copy at construction.

I understand it. 

## However, where does the argument of constructor come from?

1. If it is string literal such as "abc", the original approach is a little bit efficient. Because one move construction can omit.

```cpp
binary_property("ABC");
// create temporary std::string("ABC") and move it to `buf_` on the updated code
// the original code doesn't create temporary std::string
```
2. If it is a part of the buffer, the part of buffer can be expressed as string_view. Of course, we need to care about the buffer lifetime, but property creation is usually do synchronously

```cpp
auto buffer = "01234ABCxxxxxxx";

binary_property(string_view(&buffer[5], 3));
// The original code creates `buf_` from direct copy of the buffer
// But the updated code requires create the new string using substr() like function.
```

I think that it is a good policy that as long as we can do, mqtt_cpp keep string_view, and if std::string is actually needed, then create it.

## the return type of `val()`
The efficiency is similar. Return reference or return pointer and length. But string_view can allow efficient operation. For example, `substr()`. string_view's `sub_str()` doesn't create copy.

So I think that string_view is better for the return type of `val()`.

What do you think?

**Comment by redboltz** [comment] 2019-06-18 12:36
I asked to stackoverflow. I don't read in detail about answers but string_view is always(?) good choice for mqtt_cpp.

https://stackoverflow.com/questions/56648876/when-should-i-use-stdstring-stdstring-view-for-parameter-return-type?fbclid=IwAR0ClJZIA5uiRjmOQ7cdPEGLk8pzW4ZOKJ9imdnEq2NUy_jv2qlAo-74npg

**Comment by jonesmz** [comment] 2019-06-18 22:29
Unfortunately I suddenly have a lot going on at work this week, so I can't give you a proper answer at this time.

I will get back to you as soon as I can.

**Comment by redboltz** [comment] 2019-06-18 22:50
No problem, take your time. I don't go forward until we would make some agreement.

This theme is no only for #288 but also the base design for v5.

**Comment by jonesmz** [comment] 2019-06-24 21:44
# Constructor parameters

My default way of creating constructors to classes / structs is to have the constructor accept the arguments, by value, as the type that they are stored as in the class itself, and store them in the member variables using std::move().

Exceptions include:

- Types that are expensive to copy, and can't be std::move()ed (e.g. std::array<>)
- Types that are primitives (no reason to use std::move())
- Member variables that are stored by reference instead of value
- Member variables which have a method of construction that is not supposed to be part of the constructors API. (e.g. constructed via other function calls that the constructor makes)

My reason for this is that my class / struct can't know ahead of time all of the various ways that a user might want to construct it.

Consider a class that has a std::string as a member variable. If the class provides only a std::string_view constructor, that ensures that no user of the class will be able to provide the string data by move, requiring that an allocation and copy happen every time (except for short string optimization situations).

Consider also that this makes it more difficult for users of the class to provide the constructor parameter the way *they* want to. It could be that the user of this constructor does not actually have a std::string, or std::string_view, but instead has a class that can be implicitly converted to std::string. If I only provide the std::string_view constructor, it might not be possible for weird situations to allow the user of the class to construct my class directly. Instead requiring explicit conversions / constructions from their custom type to std::string / std::string_view.

But if I provide the user of the class the exact type that I plan to store, they can decide how to best provide me the data that I'm asking for. If they can provide that data to me in a way that doesn't require an allocation and copy, they are allowed to. If they can't do that, e.g. they only have an std::string_view, then I'm explicitly informing the user that calling my constructor will cause an allocation / copy to happen, by requiring std::string instead of std::string_view. 

Further, in mqtt_cpp, we're dealing with a header-only codebase. As a result, the compiler has 100% of the information on all constructors and their definition. I expect (this is an educated guess), that the compiler is *always* inlining the constructor for simple types like the mqtt_cpp::v5::properties, ensuring that when the parameter for the constructor is created, it's created directly into the storage location for the member variable, and no call to std::string::string(std::string&&) is made.

If std::string_view is the parameter, then the outcome might be

```std::string memberVar(std::string_view(std::move(myStdStringParameter)));```

In this situation, the compiler is forbidden from constructing `memberVar` via move, because std::string_view is being constructed in the middle of the sequence.


In your example

> ```
> binary_property("ABC");
> // create temporary std::string("ABC") and move it to `buf_` on the updated code
> // the original code doesn't create temporary std::string
> ```

This is as efficient as possible because, as I tried to explain above, the compiler has the full body of `binary_property(std::string)` available to it. While at the code level there is a temporary `std::string` being created, I would be very surprised if the compiler wasn't completely skipping that and directly constructing the member variable, with no use of a temporary `std::string`

Your second example 

> ```
> auto buffer = "01234ABCxxxxxxx";
> 
> binary_property(string_view(&buffer[5], 3));
> // The original code creates `buf_` from direct copy of the buffer
> // But the updated code requires create the new string using substr() like function.
> ```

Can be done with `std::string` just as well as it can with `std::string_view`. In both cases, the compiler should be completely ignoring the temporary variable (either `std::string` or `std::string_view`) in favor of constructing the underlying `std::string` directly.

E.g., this should work just as well, as the string_view version.

```binary_property(std::string(&buffer[5], 3));```

# Return values

Similar to the above, my philosophy is that return values should always be as close as practical to the member variable as can be.

The reason for this, which is different than with constructor parameters, is that you can trivially convert from an `std::string` -> `std::string_view`. So much so that the compiler will be able to optimize away the vast majority of the `std::string_view` code in the final executable. But going the other way around requires an allocation and copy.

If you have a function that accepts `std::string const&` (This is extremely common in legacy code bases. At my last job, functions taking `std::string const&` were 95% of the functions that involved string parameters), you can return the result of your member function directly, if the member function returns a std::string.

If you have a function that accepts `std::string_view` as the parameter, you can still use a member function returning `std::string const&` with no allocations or copies.

But the same isn't true in reverse. If your member function returns `std::string_view`, and you have a function that only accepts `std::string const&`, then you *must* either allocate/copy a new std::string, OR rewrite the function to accept `std::string_view`.

Even so, if you rewrite the function to accept `std::string_view` instead of `std::string const&`, you might have to rewrite a very large amount of code (because that function calls several other functions taking `std::string const&`, which call other functions......), and almost certainly won't actually save any runtime efficiency versus passing `std::string const&` in situations where the full body of the function is known at compile time (which is always the case for header-only libraries).

I agree with you that the extra indirection caused by the reference can add overhead in some situations, such as a large chain of function calls, spanning multiple translation units, and each of these functions takes their parameter by reference. But that's not really something that the function returning the `std::string_view` versus `std::string const&` has any control of.

Since `std::string const&` automatically / implicitly will convert to `std::string_view`, but the reverse is not true, I prefer to keep the return value of functions as close as can be to the type of the member variable being returned.

# substr

Yes, that's a possible "gotcha". My opinion is that it's the responsibility of the person using the API to use it carefully.

If the user of the API doesn't care about allocations / copies, than it doesn't matter what the mqtt_cpp api does.

If the user of the API does care about allocations / copies, than mqtt_cpp needs to involve as few allocations / copies as possible internally, and provide an API to the user that allows the user to control when allocations / copies happen.

I'd prefer a sharp knife to a dull knife, even if the sharp knife might cut me more deeply, to use poor a metaphor.

# Other issues:

As pointed out in the stackoverflow question, there are other considerations as well.

`std::string_view` is not null terminated, `std::string const&` is. While mqtt_cpp does not use any string functions that require null termination, it's not safe to assume that no user code will need that. By returning the exact type of the member variable, by const-reference, if some user code needs null termination for some reason, they can use it. (This is overwhelmingly common in legacy code bases).

Ultimately this situation is a failing on the part of the C++ standard, at least with regards to string.


# Supplimental
## Some information that I wrote several years ago, and made small edits for this post.

Strings are an interesting problem. Up to C++11, it was merely convention that led to most implementations of std::string being non-copy-on-write, but the C++11 standard mandated some performance characteristics of std::string member functions that make implementing std::string as copy-on-write impossible. Therefore, copying a std::string is an inherently deep-copy operation (incurring an allocation, and a memcpy), which can be incredibly expensive for large string objects. This aspect of the language is incredibly unlikely to change in the future, and barring implementing a new string class, we simply have to work with the existing performance characteristics.

Some C++ frameworks, like the Qt framework have adopted their own unique string type which is implemented as a copy-on-write object. This allows for passing string objects by value to functions, or “copy-constructing” string objects at very low cost, and making any code that writes to the string pay the cost of the allocate and memcpy. Of course, QString is also natively 16 bit characters, and UTF-16 throughout, which can result in a lot of extra memory usage, extra overhead converting formats, and in general is incompatible with the way the majority of modern platforms (except windows) deal with strings in APIs.

C++17 introduces the concept of a std::string_view, which is a non-owning “string,” e.g. it has the same semantics as a reference, or pointer, to the original string.

However, neither the standard library’s string, nor the qt string, nor std::string_view, either alone, or in combination, handle all of the various categories of circumstances that strings can be involved in.

**Fundamentally there are three categories we need to be concerned with. Lifetime, ownership, and mutability.**

Lifetime is all about the lifetime of the underlying string data.

- There’s some string data that lives in the read-only-data section of the binary. It’s lifetime is a proper superset of the lifetime of the program itself, as it exists before program execution, and after it, completely immutable. 
- There’s data that lives on the heap, and as such has a lifetime managed by the new and delete keywords (whether that’s happening under the hood or directly with the programmer isn’t all that important)
- There’s data that lives on the stack, with lifetime inherently limited by the conventions thereof.
- There’s also various other types of lifetime. Things like memory mapped files, shared memory with other processes, and now with the upcoming C++ standard, there’s also coroutines, which promise to throw some wrenches in things.

Ultimately, however, we’re really only concerned with whether the lifetime of data is “indefinite” or “finite”. Aside from read-only-data section data, all data has a finite lifetime, even if the program we’re executing doesn’t see the beginning or end of that lifetime. (E.g. memory mapped files, variables constructed before main() executes, so on).

Ownership is essentially the same concept as the discussion of function parameters. All data has an owner, no exceptions. Even memory leaks have an “owner”, a forgetful and poorly programmed one. The important thing we’re discussing here is whether we’re passing and/or storing string data in an owning, or non owning fashion. If a function takes a parameter passed into it, calculates something using that data, but never stores the data or a pointer to the data or a copy of the data anywhere (even if it’s storing the data in a return value), then that function is non-owning. If it does, then it’s an ownership transferring use of the parameter.

Mutability is all about whether the string can be modified via a particular variable, and the type of variable is what decides that.

So now that we’ve named the categories, let’s enumerate the possibilities with regards to function parameters and/or member variables. There are 5:

1. Data in the read-only-data section has an indefinite lifetime, cannot be owned by a variable (the owner is the the read-only-data section), and cannot be mutated. The appropriate data type for this is a std::string_view, or similar.
2. Data that is passed to a function, or stored in a struct such that the function or struct takes ownership.
- If that data needs to be mutable, then std::string, by value, is the appropriate choice, as it allows for in-place editing.
- If the data does not need to be mutable, there’s no appropriate type from the standard library, and we’ll discuss what the appropriate type looks like in a moment below.
3. Data that is passed to a function, or stored in a struct, such that the function or struct DOES NOT take ownership, but merely references the data that’s owned by something else.
- If that data needs to be mutable, then a non-const reference to std::string is the appropriate choice as it allows for in-place editing, which is the only allowable usage, since the function or struct does not take ownership and therefore the original data should be modified in place.
- If the data does not need to be mutable, then std::string_view is the appropriate choice. std::string_view inherently has no concept of ownership and provides no mechanism to mutate the data it points to, and so it’s perfect for this use case.

So that leaves us with data that needs to be owned, but is non-mutable. You could store a const std::string object, which gives you ownership and non-mutability, and in a pinch this is an ok way to go. However, this comes at the consequence of very expensive copy-construction.

We can take a page from the Qt frameworks playbook, and implement our own string type that provides 1) immutability, and 2) cheap copy-construction.

The way we do this is using reference counting semantics. Where the lifetime of the string data is either indefinite (read-only-data-section), or is data on the heap that’s owned by a reference counting smart pointer. Thus, when copies are made of this object, the reference count goes up, and when copies are destroyed, the reference count goes down. If the ref count ever hits zero, then the data is automatically destroyed and the memory freed. But it’s only possible to use ref counting, which is significantly cheaper than allocating and memcpy, because the data is immutable, which is why the complex breakdown of appropriate choices.

However, the standard library does not provide a type that can serve this function.

std::shared_ptr<std::string const> can do it, but it comes at the cost of having usage semantics that don't match all of the other string types. (e.g. have to deference the std::shared_ptr every time) while also requiring users of the class to check for nullptr, and deal with other semantic issues.

Further, std::shared_ptr<std::string const> doesn't take advantage of string data that's in the read-only-section of the binary in any way, which is just runtime efficiency left on the floor.

Better would be a class, e.g. mqtt_cpp::shared_string, that internally stored an std::shared_ptr<std::string const>, because that fixes the usage semantics problem, and allows for the mqtt__cpp::shared_string to also provide automatic conversions to std::string_view, and hide the need to check for null. But it still doesn't provide for efficiently using read-only-data-section strings.

There is a proposal for the standard library, called std::retain_ptr (poor name, in my opinion) which would provide the appropriate reference counting machinery in a standard way, allowing for some std::shared_string to be implemented in an elegant way.

But that's a bit outside the scope of mqtt_cpp, I think.

**Comment by redboltz** [comment] 2019-06-25 00:03
Thank you for the comment!! I need a time to read it carefully but my first impression is positive to use `std::string` based approach :)

**Comment by redboltz** [comment] 2019-06-28 11:12
## The return type of val

`std::string const&` is always better then `std::string_view`.

https://wandbox.org/permlink/iUIwTa2ZFLSCeA6I

User can choose type. If user want to zero copy `substr()`, user can create `std::string_view` and then call `substr()`. Null termination is not lost.

## Constructor parameter

If the class store `std::string`, then `std::string_view` and `std::string` don't have a big performance difference. In `mqtt_cpp`,most of contents are contained in `payload_`. Its lifetime is during `handle_payload()` so if `mqtt_cpp` want to use the part of payload, need to create `std::string`. If `mqtt_cpp` only refer `payload` during `handle_payload()` and create other value (such as qos) from `payload_`, `std::string_view` is better. In actual case, most of `mqtt_cpp`'s messages and properties store `std::string`. So using `std::string` is reasonable.

**Comment by jonesmz** [comment] 2019-06-28 17:52
Return value:

It's important that we only return std::string const& if the member variable itself is an std::string.

Returning an std::string_view is still better if the member variable is a std::string_view, or other non-owning type.

**Comment by jonesmz** [comment] 2019-08-19 22:14
I believe that #320 will resolve this issue as well.

**Comment by jonesmz** [comment] 2019-08-23 07:45
This issue can be closed, can't it?

**Closed** 2019-08-27 12:27 UTC
