### ISSUE TITLE
Build on Visual sudio 2017

### ISSUE THREAD

**Issue by liranHaim** [redboltz/mqtt_cpp#120] opened 2018-03-05 09:04 UTC
I try to build the c++ project.

add the include <mqtt_client_cpp.hpp> to the c++ file
Set the c++14 in the build setting
using Boost 1.66

and i get the errors:
mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(95): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::close_handler': redefinition; different basic types

what i doing wrong?

**Comment by redboltz** [comment] 2018-03-05 09:55
Unfortunately, I can't reproduce the error.

BTW, here is the example of the same error:

http://rextester.com/JCJGT47940

```cpp
#include <functional>

struct d {
    using ht = std::function<void()>;
    using ht = std::function<void(int)>; // redefinition
};

int main() {
    d d1;
}
```

```
source_file.cpp(5): error C2371: 'd::ht': redefinition; different basic types
source_file.cpp(4): note: see declaration of 'd::ht'
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23506 for x64
```
The compiler reports the redefinition point (5) and previous definition point (4).
In your case, it seems that the previous definition point is not reported.
Is that right?

**Comment by liranHaim** [comment] 2018-03-05 11:23
I don't understand,  I  just add the include and run build.
Do I miss any compiler settings?   My VS version 15.5.7
My Full errors build 
```
Info: Boost.Config is older than your compiler version - probably nothing bad will happen - but you may wish to look for an update Boost version.  Define BOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE to suppress this message.
1>Please define _WIN32_WINNT or _WIN32_WINDOWS appropriately. For example:
1>- add -D_WIN32_WINNT=0x0501 to the compiler command line; or
1>- add _WIN32_WINNT=0x0501 to your project's Preprocessor Definitions.
1>Assuming _WIN32_WINNT=0x0501 (i.e. Windows XP target).
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(95): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::close_handler': redefinition; different basic types
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(95): note: see declaration of 'mqtt::endpoint<Socket,Mutex,LockGuard>::close_handler'
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(3949): note: see reference to class template instantiation 'mqtt::endpoint<Socket,Mutex,LockGuard>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(54): note: see reference to class template instantiation 'boost::arg<9>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(53): note: see reference to class template instantiation 'boost::arg<8>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(52): note: see reference to class template instantiation 'boost::arg<7>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(51): note: see reference to class template instantiation 'boost::arg<6>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(50): note: see reference to class template instantiation 'boost::arg<5>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(49): note: see reference to class template instantiation 'boost::arg<4>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(48): note: see reference to class template instantiation 'boost::arg<3>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(47): note: see reference to class template instantiation 'boost::arg<2>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\bind\placeholders.hpp(46): note: see reference to class template instantiation 'boost::arg<1>' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\asio\use_future.hpp(138): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>::std_allocator_void' being compiled
1>d:\tests\testmqtt\boost_1_66_0\boost\asio\use_future.hpp(146): note: see reference to class template instantiation 'boost::asio::use_future_t<std::allocator<void>>' being compiled
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(292): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::pingreq_handler': redefinition; different basic types
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(292): note: see declaration of 'mqtt::endpoint<Socket,Mutex,LockGuard>::pingreq_handler'
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(300): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::pingresp_handler': redefinition; different basic types
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(300): note: see declaration of 'mqtt::endpoint<Socket,Mutex,LockGuard>::pingresp_handler'
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(307): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::disconnect_handler': redefinition; different basic types
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(307): note: see declaration of 'mqtt::endpoint<Socket,Mutex,LockGuard>::disconnect_handler'
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): error C2027: use of undefined type 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=void (__cdecl *)(void)
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): note: see declaration of 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=void (__cdecl *)(void)
1>        ]
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(3918): note: see reference to class template instantiation 'std::function<void (__cdecl *)(void)>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(680): error C2504: 'type': base class undefined
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(682): error C2027: use of undefined type 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=void (__cdecl *)(void)
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): note: see declaration of 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=void (__cdecl *)(void)
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(682): error C3646: '_Mybase': unknown override specifier
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(682): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): error C2027: use of undefined type 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=bool (__cdecl *)(void)
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): note: see declaration of 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=bool (__cdecl *)(void)
1>        ]
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(3932): note: see reference to class template instantiation 'std::function<bool (__cdecl *)(void)>' being compiled
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(682): error C2027: use of undefined type 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=bool (__cdecl *)(void)
1>        ]
1>c:\program files (x86)\microsoft visual studio\2017\professional\vc\tools\msvc\14.12.25827\include\functional(679): note: see declaration of 'std::_Get_function_impl<_Fty>'
1>        with
1>        [
1>            _Fty=bool (__cdecl *)(void)
1>        ]
1>Done building project "MqttClientLib.vcxproj" -- FAILED.
```

**Comment by redboltz** [comment] 2018-03-05 13:14
```
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(95): error C2371: 'mqtt::endpoint<Socket,Mutex,LockGuard>::close_handler': redefinition; different basic types
1>d:\tests\testmqtt\testmqttcpp\mqtt_cpp-2.0.0\include\mqtt\endpoint.hpp(95): note: see declaration of 'mqtt::endpoint<Socket,Mutex,LockGuard>::close_handler'
```

indicates the redefinition and the previous definition are the same line of code. I don't understand what happened. 
I'm not sure how to solve the problem. But it's worth trying other version of MSVC.

**Comment by redboltz** [comment] 2018-03-05 13:16
mqtt_cpp is successfully compiled and run on MSVC 2017 on appveyor.

https://github.com/redboltz/mqtt_cpp/blob/master/appveyor.yml
might help you.

**Comment by liranHaim** [comment] 2018-03-05 14:58
I manage to build the project by change the lines for using = to typedef 
`using close_handler = std::function<void()>; to typedef std::function<void()> close_handler;`
is that OK?

**Comment by redboltz** [comment] 2018-03-05 15:18
It's the same meaning. You can change in your project locally.
If MSVC supports C++14, using shouldn't make the error. I think that it is MSVC's bug or option setting problem.

**Comment by jonesmz** [comment] 2019-04-26 08:30
@liranHaim is this still a problem for you?

**Comment by ephlodur2** [comment] 2019-05-28 01:17
Sorry to ask question in this thread also ... I'm also having issue with running the mqtt lib with Visual 2017
I'm not sure if I'm setting the handler wrong or if this another issue.
for now I get a C++ exception: std::bad_function_call at memory location

when I try to I do a io.run()
I think this may be link to the setup of the handler this is an example of how I setup the connack
 m_MQTTClient->set_connack_handler( boost::bind( &SOA_MQTT_Client::ConnackHandler, this, _1,_2) );

the io service is a private member
 boost::asio::io_service  m_ioService;

Any help to point me in the right direction is very appreciated

**Comment by redboltz** [comment] 2019-05-28 01:55
@ephlodur2 , it is another issue because you got runtime error but this issue is compile error.
Could you create a new issue?
And then, please post minimal and complete code that reproduces the problem. It is difficult to help you without the code.

**Comment by redboltz** [comment] 2019-08-27 12:33
I close the issue.
@liranHaim , if you still have the problem, please post a comment and reopen the issue.

**Closed by redboltz** 2019-08-27 12:33 UTC
